version: '2'
services:
    musiccloud-app:
        image: musiccloud
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://musiccloud-mysql:3306/musiccloud?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=musiccloud-elasticsearch:9300
        ports:
            - 8080:8080
    musiccloud-mysql:
        extends:
            file: mysql.yml
            service: musiccloud-mysql
    musiccloud-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: musiccloud-elasticsearch
